language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libtest-differences-perl

env:
  - BUILD_TYPE="Debug"
  - BUILD_TYPE="Release"

script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX="../_install" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" $OPTIONS ..
  - cmake --build .
  - cmake --build . --target install
